// Copyright 2014 beego Author. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package web

var mimemaps = map[string]string{
	".3dm":         literal_9173,
	".3dmf":        literal_9173,
	".7z":          "application/x-7z-compressed",
	".a":           literal_0243,
	".aab":         "application/x-authorware-bin",
	".aam":         "application/x-authorware-map",
	".aas":         "application/x-authorware-seg",
	".abc":         "text/vndabc",
	".ace":         "application/x-ace-compressed",
	".acgi":        literal_0867,
	".afl":         "video/animaflex",
	".ai":          literal_5371,
	".aif":         literal_5147,
	".aifc":        literal_5147,
	".aiff":        literal_5147,
	".aim":         "application/x-aim",
	".aip":         "text/x-audiosoft-intra",
	".alz":         "application/x-alz-compressed",
	".ani":         "application/x-navi-animation",
	".aos":         "application/x-nokia-9000-communicator-add-on-software",
	".aps":         "application/mime",
	".apk":         "application/vnd.android.package-archive",
	".arc":         "application/x-arc-compressed",
	".arj":         "application/arj",
	".art":         "image/x-jg",
	".asf":         "video/x-ms-asf",
	".asm":         "text/x-asm",
	".asp":         "text/asp",
	".asx":         "application/x-mplayer2",
	".au":          "audio/basic",
	".avi":         "video/x-msvideo",
	".avs":         "video/avs-video",
	".bcpio":       "application/x-bcpio",
	".bin":         "application/mac-binary",
	".bmp":         "image/bmp",
	".boo":         "application/book",
	".book":        "application/book",
	".boz":         "application/x-bzip2",
	".bsh":         "application/x-bsh",
	".bz2":         "application/x-bzip2",
	".bz":          "application/x-bzip",
	".c++":         literal_7253,
	".c":           literal_6491,
	".cab":         "application/vnd.ms-cab-compressed",
	".cat":         "application/vndms-pkiseccat",
	".cc":          literal_6491,
	".ccad":        "application/clariscad",
	".cco":         "application/x-cocoa",
	".cdf":         "application/cdf",
	".cer":         "application/pkix-cert",
	".cha":         "application/x-chat",
	".chat":        "application/x-chat",
	".chrt":        "application/vnd.kde.kchart",
	".class":       "application/java",
	".com":         literal_7253,
	".conf":        literal_7253,
	".cpio":        "application/x-cpio",
	".cpp":         literal_6491,
	".cpt":         "application/mac-compactpro",
	".crl":         "application/pkcs-crl",
	".crt":         "application/pkix-cert",
	".crx":         "application/x-chrome-extension",
	".csh":         "text/x-scriptcsh",
	".css":         "text/css",
	".csv":         "text/csv",
	".cxx":         literal_7253,
	".dar":         "application/x-dar",
	".dcr":         literal_6108,
	".deb":         "application/x-debian-package",
	".deepv":       "application/x-deepv",
	".def":         literal_7253,
	".der":         "application/x-x509-ca-cert",
	".dif":         "video/x-dv",
	".dir":         literal_6108,
	".divx":        "video/divx",
	".dl":          "video/dl",
	".dmg":         "application/x-apple-diskimage",
	".doc":         literal_8067,
	".dot":         literal_8067,
	".dp":          "application/commonground",
	".drw":         "application/drafting",
	".dump":        literal_0243,
	".dv":          "video/x-dv",
	".dvi":         "application/x-dvi",
	".dwf":         "drawing/x-dwf=(old)",
	".dwg":         "application/acad",
	".dxf":         "application/dxf",
	".dxr":         literal_6108,
	".el":          "text/x-scriptelisp",
	".elc":         "application/x-bytecodeelisp=(compiled=elisp)",
	".eml":         literal_2096,
	".env":         "application/x-envoy",
	".eps":         literal_5371,
	".es":          "application/x-esrehber",
	".etx":         "text/x-setext",
	".evy":         "application/envoy",
	".exe":         literal_0243,
	".f77":         literal_3546,
	".f90":         literal_3546,
	".f":           literal_3546,
	".fdf":         "application/vndfdf",
	".fif":         "application/fractals",
	".fli":         "video/fli",
	".flo":         "image/florian",
	".flv":         "video/x-flv",
	".flx":         "text/vndfmiflexstor",
	".fmf":         "video/x-atomic3d-feature",
	".for":         literal_3546,
	".fpx":         "image/vndfpx",
	".frl":         "application/freeloader",
	".funk":        literal_4638,
	".g3":          "image/g3fax",
	".g":           literal_7253,
	".gif":         "image/gif",
	".gl":          "video/gl",
	".gsd":         "audio/x-gsm",
	".gsm":         "audio/x-gsm",
	".gsp":         "application/x-gsp",
	".gss":         "application/x-gss",
	".gtar":        "application/x-gtar",
	".gz":          "application/x-compressed",
	".gzip":        "application/x-gzip",
	".h":           "text/x-h",
	".hdf":         "application/x-hdf",
	".help":        "application/x-helpfile",
	".hgl":         literal_9738,
	".hh":          "text/x-h",
	".hlb":         "text/x-script",
	".hlp":         "application/hlp",
	".hpg":         literal_9738,
	".hpgl":        literal_9738,
	".hqx":         "application/binhex",
	".hta":         "application/hta",
	".htc":         "text/x-component",
	".htm":         literal_0867,
	".html":        literal_0867,
	".htmls":       literal_0867,
	".htt":         "text/webviewhtml",
	".htx":         literal_0867,
	".ice":         "x-conference/x-cooltalk",
	".ico":         "image/x-icon",
	".ics":         "text/calendar",
	".icz":         "text/calendar",
	".idc":         literal_7253,
	".ief":         "image/ief",
	".iefs":        "image/ief",
	".iges":        "application/iges",
	".igs":         "application/iges",
	".ima":         "application/x-ima",
	".imap":        "application/x-httpd-imap",
	".inf":         "application/inf",
	".ins":         "application/x-internett-signup",
	".ip":          "application/x-ip2",
	".isu":         "video/x-isvideo",
	".it":          "audio/it",
	".iv":          "application/x-inventor",
	".ivr":         "i-world/i-vrml",
	".ivy":         "application/x-livescreen",
	".jam":         "audio/x-jam",
	".jav":         "text/x-java-source",
	".java":        "text/x-java-source",
	".jcm":         "application/x-java-commerce",
	".jfif-tbnl":   literal_5370,
	".jfif":        literal_5370,
	".jnlp":        "application/x-java-jnlp-file",
	".jpe":         literal_5370,
	".jpeg":        literal_5370,
	".jpg":         literal_5370,
	".jps":         "image/x-jps",
	".js":          "application/javascript",
	".json":        "application/json",
	".jut":         "image/jutvision",
	".kar":         "audio/midi",
	".karbon":      "application/vnd.kde.karbon",
	".kfo":         "application/vnd.kde.kformula",
	".flw":         "application/vnd.kde.kivio",
	".kml":         "application/vnd.google-earth.kml+xml",
	".kmz":         "application/vnd.google-earth.kmz",
	".kon":         "application/vnd.kde.kontour",
	".kpr":         "application/vnd.kde.kpresenter",
	".kpt":         "application/vnd.kde.kpresenter",
	".ksp":         "application/vnd.kde.kspread",
	".kwd":         "application/vnd.kde.kword",
	".kwt":         "application/vnd.kde.kword",
	".ksh":         "text/x-scriptksh",
	".la":          "audio/nspaudio",
	".lam":         "audio/x-liveaudio",
	".latex":       "application/x-latex",
	".lha":         "application/lha",
	".lhx":         literal_0243,
	".list":        literal_7253,
	".lma":         "audio/nspaudio",
	".log":         literal_7253,
	".lsp":         "text/x-scriptlisp",
	".lst":         literal_7253,
	".lsx":         "text/x-la-asf",
	".ltx":         "application/x-latex",
	".lzh":         literal_0243,
	".lzx":         "application/lzx",
	".m1v":         literal_7195,
	".m2a":         literal_4207,
	".m2v":         literal_7195,
	".m3u":         "audio/x-mpegurl",
	".m":           "text/x-m",
	".man":         "application/x-troff-man",
	".manifest":    "text/cache-manifest",
	".map":         "application/x-navimap",
	".mar":         literal_7253,
	".mbd":         "application/mbedlet",
	".mc$":         "application/x-magic-cap-package-10",
	".mcd":         "application/mcad",
	".mcf":         "text/mcf",
	".mcp":         "application/netmc",
	".me":          "application/x-troff-me",
	".mht":         literal_2096,
	".mhtml":       literal_2096,
	".mid":         "application/x-midi",
	".midi":        "application/x-midi",
	".mif":         "application/x-frame",
	".mime":        literal_2096,
	".mjf":         "audio/x-vndaudioexplosionmjuicemediafile",
	".mjpg":        "video/x-motion-jpeg",
	".mm":          "application/base64",
	".mme":         "application/base64",
	".mod":         "audio/mod",
	".moov":        literal_9703,
	".mov":         literal_9703,
	".movie":       "video/x-sgi-movie",
	".mp2":         literal_4207,
	".mp3":         "audio/mpeg3",
	".mp4":         "video/mp4",
	".mpa":         literal_4207,
	".mpc":         literal_7263,
	".mpe":         literal_7195,
	".mpeg":        literal_7195,
	".mpg":         literal_7195,
	".mpga":        literal_4207,
	".mpp":         "application/vndms-project",
	".mpt":         literal_7263,
	".mpv":         literal_7263,
	".mpx":         literal_7263,
	".mrc":         "application/marc",
	".ms":          "application/x-troff-ms",
	".mv":          "video/x-sgi-movie",
	".my":          literal_4638,
	".mzz":         "application/x-vndaudioexplosionmzz",
	".nap":         "image/naplps",
	".naplps":      "image/naplps",
	".nc":          "application/x-netcdf",
	".ncm":         "application/vndnokiaconfiguration-message",
	".nif":         "image/x-niff",
	".niff":        "image/x-niff",
	".nix":         "application/x-mix-transfer",
	".nsc":         "application/x-conference",
	".nvd":         "application/x-navidoc",
	".o":           literal_0243,
	".oda":         "application/oda",
	".odb":         "application/vnd.oasis.opendocument.database",
	".odc":         "application/vnd.oasis.opendocument.chart",
	".odf":         "application/vnd.oasis.opendocument.formula",
	".odg":         "application/vnd.oasis.opendocument.graphics",
	".odi":         "application/vnd.oasis.opendocument.image",
	".odm":         "application/vnd.oasis.opendocument.text-master",
	".odp":         "application/vnd.oasis.opendocument.presentation",
	".ods":         "application/vnd.oasis.opendocument.spreadsheet",
	".odt":         "application/vnd.oasis.opendocument.text",
	".oga":         literal_5981,
	".ogg":         literal_5981,
	".ogv":         "video/ogg",
	".omc":         "application/x-omc",
	".omcd":        "application/x-omcdatamaker",
	".omcr":        "application/x-omcregerator",
	".otc":         "application/vnd.oasis.opendocument.chart-template",
	".otf":         "application/vnd.oasis.opendocument.formula-template",
	".otg":         "application/vnd.oasis.opendocument.graphics-template",
	".oth":         "application/vnd.oasis.opendocument.text-web",
	".oti":         "application/vnd.oasis.opendocument.image-template",
	".otm":         "application/vnd.oasis.opendocument.text-master",
	".otp":         "application/vnd.oasis.opendocument.presentation-template",
	".ots":         "application/vnd.oasis.opendocument.spreadsheet-template",
	".ott":         "application/vnd.oasis.opendocument.text-template",
	".p10":         "application/pkcs10",
	".p12":         "application/pkcs-12",
	".p7a":         "application/x-pkcs7-signature",
	".p7c":         "application/pkcs7-mime",
	".p7m":         "application/pkcs7-mime",
	".p7r":         "application/x-pkcs7-certreqresp",
	".p7s":         "application/pkcs7-signature",
	".p":           "text/x-pascal",
	".part":        "application/pro_eng",
	".pas":         "text/pascal",
	".pbm":         "image/x-portable-bitmap",
	".pcl":         "application/vndhp-pcl",
	".pct":         "image/x-pict",
	".pcx":         "image/x-pcx",
	".pdb":         "chemical/x-pdb",
	".pdf":         "application/pdf",
	".pfunk":       literal_4638,
	".pgm":         "image/x-portable-graymap",
	".pic":         "image/pict",
	".pict":        "image/pict",
	".pkg":         "application/x-newton-compatible-pkg",
	".pko":         "application/vndms-pkipko",
	".pl":          "text/x-scriptperl",
	".plx":         "application/x-pixclscript",
	".pm4":         "application/x-pagemaker",
	".pm5":         "application/x-pagemaker",
	".pm":          "text/x-scriptperl-module",
	".png":         "image/png",
	".pnm":         "application/x-portable-anymap",
	".pot":         literal_4967,
	".pov":         "model/x-pov",
	".ppa":         "application/vndms-powerpoint",
	".ppm":         "image/x-portable-pixmap",
	".pps":         literal_4967,
	".ppt":         literal_4967,
	".ppz":         literal_4967,
	".pre":         "application/x-freelance",
	".prt":         "application/pro_eng",
	".ps":          literal_5371,
	".psd":         literal_0243,
	".pvu":         "paleovu/x-pv",
	".pwz":         "application/vndms-powerpoint",
	".py":          "text/x-scriptphyton",
	".pyc":         "application/x-bytecodepython",
	".qcp":         "audio/vndqcelp",
	".qd3":         literal_9173,
	".qd3d":        literal_9173,
	".qif":         literal_9027,
	".qt":          literal_9703,
	".qtc":         "video/x-qtc",
	".qti":         literal_9027,
	".qtif":        literal_9027,
	".ra":          literal_1920,
	".ram":         literal_1920,
	".rar":         "application/x-rar-compressed",
	".ras":         "application/x-cmu-raster",
	".rast":        "image/cmu-raster",
	".rexx":        "text/x-scriptrexx",
	".rf":          "image/vndrn-realflash",
	".rgb":         "image/x-rgb",
	".rm":          "application/vndrn-realmedia",
	".rmi":         "audio/mid",
	".rmm":         literal_1920,
	".rmp":         literal_1920,
	".rng":         "application/ringing-tones",
	".rnx":         "application/vndrn-realplayer",
	".roff":        literal_5386,
	".rp":          "image/vndrn-realpix",
	".rpm":         "audio/x-pn-realaudio-plugin",
	".rt":          "text/vndrn-realtext",
	".rtf":         "text/richtext",
	".rtx":         "text/richtext",
	".rv":          "video/vndrn-realvideo",
	".s":           "text/x-asm",
	".s3m":         "audio/s3m",
	".s7z":         "application/x-7z-compressed",
	".saveme":      literal_0243,
	".sbk":         "application/x-tbook",
	".scm":         "text/x-scriptscheme",
	".sdml":        literal_7253,
	".sdp":         "application/sdp",
	".sdr":         "application/sounder",
	".sea":         "application/sea",
	".set":         "application/set",
	".sgm":         "text/x-sgml",
	".sgml":        "text/x-sgml",
	".sh":          "text/x-scriptsh",
	".shar":        "application/x-bsh",
	".shtml":       "text/x-server-parsed-html",
	".sid":         "audio/x-psid",
	".skd":         literal_9546,
	".skm":         literal_9546,
	".skp":         literal_9546,
	".skt":         literal_9546,
	".sit":         "application/x-stuffit",
	".sitx":        "application/x-stuffitx",
	".sl":          "application/x-seelogo",
	".smi":         "application/smil",
	".smil":        "application/smil",
	".snd":         "audio/basic",
	".sol":         "application/solids",
	".spc":         "text/x-speech",
	".spl":         "application/futuresplash",
	".spr":         "application/x-sprite",
	".sprite":      "application/x-sprite",
	".spx":         literal_5981,
	".src":         "application/x-wais-source",
	".ssi":         "text/x-server-parsed-html",
	".ssm":         "application/streamingmedia",
	".sst":         "application/vndms-pkicertstore",
	".step":        "application/step",
	".stl":         "application/sla",
	".stp":         "application/step",
	".sv4cpio":     "application/x-sv4cpio",
	".sv4crc":      "application/x-sv4crc",
	".svf":         "image/vnddwg",
	".svg":         "image/svg+xml",
	".svr":         "application/x-world",
	".swf":         "application/x-shockwave-flash",
	".t":           literal_5386,
	".talk":        "text/x-speech",
	".tar":         "application/x-tar",
	".tbk":         "application/toolbook",
	".tcl":         "text/x-scripttcl",
	".tcsh":        "text/x-scripttcsh",
	".tex":         "application/x-tex",
	".texi":        "application/x-texinfo",
	".texinfo":     "application/x-texinfo",
	".text":        literal_7253,
	".tgz":         "application/gnutar",
	".tif":         "image/tiff",
	".tiff":        "image/tiff",
	".tr":          literal_5386,
	".tsi":         "audio/tsp-audio",
	".tsp":         "application/dsptype",
	".tsv":         "text/tab-separated-values",
	".turbot":      "image/florian",
	".txt":         literal_7253,
	".uil":         "text/x-uil",
	".uni":         literal_4869,
	".unis":        literal_4869,
	".unv":         "application/i-deas",
	".uri":         literal_4869,
	".uris":        literal_4869,
	".ustar":       "application/x-ustar",
	".uu":          "text/x-uuencode",
	".uue":         "text/x-uuencode",
	".vcd":         "application/x-cdlink",
	".vcf":         "text/x-vcard",
	".vcard":       "text/x-vcard",
	".vcs":         "text/x-vcalendar",
	".vda":         "application/vda",
	".vdo":         "video/vdo",
	".vew":         "application/groupwise",
	".viv":         "video/vivo",
	".vivo":        "video/vivo",
	".vmd":         "application/vocaltec-media-desc",
	".vmf":         "application/vocaltec-media-file",
	".voc":         "audio/voc",
	".vos":         "video/vosaic",
	".vox":         "audio/voxware",
	".vqe":         "audio/x-twinvq-plugin",
	".vqf":         "audio/x-twinvq",
	".vql":         "audio/x-twinvq-plugin",
	".vrml":        "application/x-vrml",
	".vrt":         "x-world/x-vrt",
	".vsd":         literal_3027,
	".vst":         literal_3027,
	".vsw":         literal_3027,
	".w60":         "application/wordperfect60",
	".w61":         "application/wordperfect61",
	".w6w":         literal_8067,
	".wav":         "audio/wav",
	".wb1":         "application/x-qpro",
	".wbmp":        "image/vnd.wap.wbmp",
	".web":         "application/vndxara",
	".wiz":         literal_8067,
	".wk1":         "application/x-123",
	".wmf":         "windows/metafile",
	".wml":         "text/vnd.wap.wml",
	".wmlc":        "application/vnd.wap.wmlc",
	".wmls":        "text/vnd.wap.wmlscript",
	".wmlsc":       "application/vnd.wap.wmlscriptc",
	".word":        literal_8067,
	".wp5":         literal_2375,
	".wp6":         literal_2375,
	".wp":          literal_2375,
	".wpd":         literal_2375,
	".wq1":         "application/x-lotus",
	".wri":         "application/mswrite",
	".wrl":         "application/x-world",
	".wrz":         "model/vrml",
	".wsc":         "text/scriplet",
	".wsrc":        "application/x-wais-source",
	".wtk":         "application/x-wintalk",
	".x-png":       "image/png",
	".xbm":         "image/x-xbitmap",
	".xdr":         "video/x-amt-demorun",
	".xgz":         "xgl/drawing",
	".xif":         "image/vndxiff",
	".xl":          literal_6580,
	".xla":         literal_6580,
	".xlb":         literal_6580,
	".xlc":         literal_6580,
	".xld":         literal_6580,
	".xlk":         literal_6580,
	".xll":         literal_6580,
	".xlm":         literal_6580,
	".xls":         literal_6580,
	".xlt":         literal_6580,
	".xlv":         literal_6580,
	".xlw":         literal_6580,
	".xm":          "audio/xm",
	".xml":         "text/xml",
	".xmz":         "xgl/movie",
	".xpix":        "application/x-vndls-xpix",
	".xpm":         "image/x-xpixmap",
	".xsr":         "video/x-amt-showrun",
	".xwd":         "image/x-xwd",
	".xyz":         "chemical/x-pdb",
	".z":           "application/x-compress",
	".zip":         "application/zip",
	".zoo":         literal_0243,
	".zsh":         "text/x-scriptzsh",
	".docx":        "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
	".docm":        "application/vnd.ms-word.document.macroEnabled.12",
	".dotx":        "application/vnd.openxmlformats-officedocument.wordprocessingml.template",
	".dotm":        "application/vnd.ms-word.template.macroEnabled.12",
	".xlsx":        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
	".xlsm":        "application/vnd.ms-excel.sheet.macroEnabled.12",
	".xltx":        "application/vnd.openxmlformats-officedocument.spreadsheetml.template",
	".xltm":        "application/vnd.ms-excel.template.macroEnabled.12",
	".xlsb":        "application/vnd.ms-excel.sheet.binary.macroEnabled.12",
	".xlam":        "application/vnd.ms-excel.addin.macroEnabled.12",
	".pptx":        "application/vnd.openxmlformats-officedocument.presentationml.presentation",
	".pptm":        "application/vnd.ms-powerpoint.presentation.macroEnabled.12",
	".ppsx":        "application/vnd.openxmlformats-officedocument.presentationml.slideshow",
	".ppsm":        "application/vnd.ms-powerpoint.slideshow.macroEnabled.12",
	".potx":        "application/vnd.openxmlformats-officedocument.presentationml.template",
	".potm":        "application/vnd.ms-powerpoint.template.macroEnabled.12",
	".ppam":        "application/vnd.ms-powerpoint.addin.macroEnabled.12",
	".sldx":        "application/vnd.openxmlformats-officedocument.presentationml.slide",
	".sldm":        "application/vnd.ms-powerpoint.slide.macroEnabled.12",
	".thmx":        "application/vnd.ms-officetheme",
	".onetoc":      literal_5486,
	".onetoc2":     literal_5486,
	".onetmp":      literal_5486,
	".onepkg":      literal_5486,
	".key":         "application/x-iwork-keynote-sffkey",
	".kth":         "application/x-iwork-keynote-sffkth",
	".nmbtemplate": "application/x-iwork-numbers-sfftemplate",
	".numbers":     "application/x-iwork-numbers-sffnumbers",
	".pages":       "application/x-iwork-pages-sffpages",
	".template":    "application/x-iwork-pages-sfftemplate",
	".xpi":         "application/x-xpinstall",
	".oex":         "application/x-opera-extension",
	".mustache":    literal_0867,
}

const literal_9173 = "x-world/x-3dmf"

const literal_0243 = "application/octet-stream"

const literal_0867 = "text/html"

const literal_5371 = "application/postscript"

const literal_5147 = "audio/aiff"

const literal_7253 = "text/plain"

const literal_6491 = "text/x-c"

const literal_6108 = "application/x-director"

const literal_8067 = "application/msword"

const literal_2096 = "message/rfc822"

const literal_3546 = "text/x-fortran"

const literal_4638 = "audio/make"

const literal_9738 = "application/vndhp-hpgl"

const literal_5370 = "image/jpeg"

const literal_7195 = "video/mpeg"

const literal_4207 = "audio/mpeg"

const literal_9703 = "video/quicktime"

const literal_7263 = "application/x-project"

const literal_5981 = "audio/ogg"

const literal_4967 = "application/mspowerpoint"

const literal_9027 = "image/x-quicktime"

const literal_1920 = "audio/x-pn-realaudio"

const literal_5386 = "application/x-troff"

const literal_9546 = "application/x-koan"

const literal_4869 = "text/uri-list"

const literal_3027 = "application/x-visio"

const literal_2375 = "application/wordperfect"

const literal_6580 = "application/excel"

const literal_5486 = "application/onenote"
